// static weapon definitions; rates in shots/sec, damage per hit (per pellet
// for the shotgun), spread in radians, reload in seconds
export const WEAPONS = {
  bat: {
    name: "Bat",
    kind: "melee",
    damage: 35,
    rate: 1.4,
    range: 2.3,
    arc: 1.2,
    stamina: 14,
    knock: 3,
  },
  pistol: {
    name: "Pistol",
    kind: "gun",
    damage: 26,
    rate: 4,
    auto: false,
    mag: 12,
    ammo: "9mm",
    pellets: 1,
    spread: 0.012,
    range: 80,
    reload: 1.1,
    headMult: 2.2,
    knock: 0.8,
    kick: 0.016,
  },
  shotgun: {
    name: "Shotgun",
    kind: "gun",
    damage: 12,
    rate: 1.0,
    auto: false,
    mag: 6,
    ammo: "shell",
    pellets: 7,
    spread: 0.055,
    range: 38,
    reload: 2.0,
    headMult: 1.5,
    knock: 2.2,
    kick: 0.05,
  },
  rifle: {
    name: "Rifle",
    kind: "gun",
    damage: 16,
    rate: 8.5,
    auto: true,
    mag: 30,
    ammo: "5.56",
    pellets: 1,
    spread: 0.02,
    range: 90,
    reload: 1.7,
    headMult: 1.8,
    knock: 0.6,
    kick: 0.013,
  },
};

export const SLOT_ORDER = ["bat", "pistol", "shotgun", "rifle"];
